title: Patrick Cuba, IT Architect
email: patrick.m.cuba@slu.edu
description: >- # this means to ignore newlines until "baseurl:"
  As a member of the Reserach Computing Group, I design and implement tools, 
  services, and software for use by researchers, students, and the public.
baseurl: "/whoami" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cubap

# Build settings
theme: minima
